---
- name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
  include_vars:
    file: osmap.yaml
    name: osmap
- name: Install ZeroTier (DEB)
  include_tasks: install_deb.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install ZeroTier (RPM)
  include_tasks: install_rpm.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable ZeroTier Service
  systemd:
    name: zerotier-one
    state: started
    enabled: yes

- name: Wait for ZeroTier to generate identity
  wait_for:
    path: /var/lib/zerotier-one/identity.secret

- name: Perform Local Config
  include_tasks: local_config.yml

- name: Setup ZeroTier Network 
  zerotier:
    apikey: "{{item.value.apikey | default('')}}"
    nodename: "{{item.value.nodename | default(inventory_hostname)}}"
    nodedescription: "{{item.value.nodedescription | default('')}}"
    config: "{{item.value.config | default('{}')}}"
    hidden: "{{item.value.hidden | default(False)}}"
    joined: "{{item.value.joined| default(True)}}"
  loop: "{{lookup('dict', zerotier_networks, wantlist=True)}}"
  loop_control:
    label: "{{ item.key }}"
