---
scenario: {}
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: ubuntu2004
    box: generic/ubuntu2004
  - name: ubuntu1804
    box: generic/ubuntu1804
provisioner:
  name: ansible
verifier:
  name: ansible
