---
scenario: {}
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: vbox
platforms:
  - name: test
    box: generic/ubuntu2004
provisioner:
  name: ansible
  config_options:
    defaults:
      display_args_to_stdout: False
verifier:
  name: ansible
