---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
platforms:
  - name: ubuntu-2004
    hostname: ubuntu-2004
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
      synced_folder: true
    box: generic/ubuntu2004
    box_version: 4.2.16
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
verifier:
  name: ansible
